### ISSUE TITLE
Circos checklist

### ISSUE THREAD

**Issue by erichartline** [dictybase-playground/dictyaccess#12]
- [x] Make images clickable w/ redirect to full diagram
- [ ] Add working dropdown/select menus
- [ ] Solve issue with rendering thumbnails (possibly with web workers?)
- [ ] Cut down on white space
- [x] Make wireframes
- [ ] Make data stay rendered after mounting
- [ ] Add zoom feature
- [ ] Figure out how to click data and open page

Zoom feature possibility: https://github.com/chrvadala/react-svg-pan-zoom

**Comment by erichartline** [comment]
Closing since app has been moved to [/dictybase](https://github.com/dictyBase/dictyaccess)
